# ArwencMC ServerCore Configuration
database:
  database_type: mysql # mysql or mongodb
  host: ""
  port: 3306
  databse: ""
  username: ""
  password: ""
general:
  not_player: "&cYou must be a player in order to use this command."
  no_permission: "&cYou do not have permission to use this command."
