# ArwencMC ServerCore Configuration
database:
  database_type: mysql # mysql or mongodb
  host: ""
  port: 3306 # make sure to change this if you are using MongoDB
  databse: ""
  username: ""
  password: ""
general:
  not_player: "&cYou must be a player in order to use this command."
  no_permission: "&cYou do not have permission to use this command."
  missing_argument: "&cYou are missing an argument. Please check the usage."
  unkown_argument: "&cThe argument you provided is unknown. Please check the usage."
  prefix: "&7[&5Arwen&7] "
  player_offline: "&cThe player specified is not online."
  admin_permission: "servercore.admin" # the default permisson node that is used. feel free to change this but make to update your own permission system.
  player_permission: "servercore.player" # ^
features:
  fly:
    fly_enable: true
    fly_enabled: "&aYour flight mode has been enabled."
    fly_disabled: "&cYour flight mode has been disabled."
  welcome:
    welcome_enable: true
    welcome_back_messages: true # Send any welcome back messages.
    welcome_actionbar_messages: false # Send any actionbar messages
    actionbar_welcome: "&aWelcome to ArwenMC!"
    actionbar_welcome_back: "&aWelcome back to ArwenMC!"
    welcome_broadcast_server_message: false # Should we broadcast a message to the server when a player comes back.
    welcome_broadcast_message: "&aEveryone please welcome {Player} to the Server!"
    welcome_back_broadcast_message: "&aWelcome back {Player} to the Server"
  gamemode:
    gamemode_enable: false
    gamemode_log: console # Log changes to either console or database or false
    gm_0: "&7Your gamemode is now &csurvival"
    gm_1: "&7Your gamemode is now &acreative"
    gm_3: "&7Your gamemode is now &4adventure"
    gm_4: "&7Your gamemode is now &6spectator"
    gamemode_actionbar_enable: true # Enable the sending of actionbar messages when the user changes gamemode.
    gamemode_actionbar_same_messages: true # Use the same messages for both the actionbar and chat.
  chat:
    mutechat_enable: true
    chat_muted: "&cChat is muted." # Triggered if some tries to talk while chat is muted.
    chat_now_muted: "&cChat muted is now turned on."
    chat_now_unmuted: "&aChat muted is now turend off."
  help:
    help_enable: true
    messages:
      - "&aHelp is always there if you need it."
      - "&aContact a member of Staff."
