name: Server-Core
version: 0.1
author: ArwenMC
authors: ["Alexander Milanovich"]
main: io.github.Arwen.Main
commands:
  fly:
    usage: /fly
    description: Command Which Allows Player To Fly!
  gamemode:
    aliases: [gm]
    usuage: /gamemode
    description: Command Which Allows Player To Switch Gamemodes!
  help:
    aliases: [?]
    usuage: /help
    description: Command Which Helps Players!
  MuteChat:
    usuage: /MuteChat
    description: Stop Players from chating!
  Spawn:
    usuage: /Spawn
    description: Teleports Players to spawn!
  SetSpawn:
    usuage: /SetSpawn
    description: Sets the world spawn!
  EntitySpawn:
    usuage: /EntitySpawn
    description: A test command to check if the API is working
  BannerBuilder:
    usuage: /BannerBuilder
    description: A test command to check if the API is working
  PotionSpawn:
    usuage: /Potionspawn
    description: A test command to check if the API is working
  EggSpawn:
    usuage: /EggSpawn
    description: A test command to check if the API is working
  FireworkSpawn:
    usuage: /FireworkSpawn
    description: A test command to check if the API is working