name: ServerCore
version: 1.2
author: ArwenMC
authors: ["Alexander Milanovich", "Christopher Nethercott"]
main: com.arwenmc.ServerCore
commands:
  servercoretest:
    usage: /servercoretest
    description: A test command.
  togglegui:
    usage: /togglegui
    description: An example command of how to implement a togglegui.