name: ServerCore
version: 1.2.1
author: ArwenMC
authors: ["Alexander Milanovich", "Christopher Nethercott"]
main: com.arwenmc.ServerCore
commands:
  servercore:
    usage: /servercore
    description: A util command.
  togglegui:
    usage: /togglegui
    description: An example command of how to implement a togglegui.